---
- name: setup flask 
  hosts: localhost
  become: true 
  
  tasks: 
  - name: Update package lists 
    apt: 
     update_cache: yes 

  - name: Install pip3 
    apt: 
     name: python3-pip 
     state: present 
     
  - name: Create a virtual environment
      command: python3 -m venv venv
      args:
        chdir: /home/ubuntu/gc

  - name: Activate virtual environment and install Flask
      shell: |
        source venv/bin/activate
        pip install Flask
      args:
        chdir: /home/ubuntu/gc

  - name: Install Flask 
    pip: 
     name: Flask 
     state: present

  - name: Execute python script 
    command: python3 app.py &
