---
- name: Setup Flask Application
  hosts: localhost
  become: true

  tasks:
    - name: Update package lists
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - python3-venv
          - python3-pip
          - python3-full
        state: present

    - name: Create a virtual environment
      command: python3 -m venv venv
      args:
        chdir: /home/ubuntu/gc

    - name: Activate virtual environment and install Flask
      shell: |
        source venv/bin/activate && pip install Flask
      args:
        chdir: /home/ubuntu/gc
        executable: /bin/bash

    - name: Run Flask application
      shell: |
        source venv/bin/activate && nohup python3 app.py &
      args:
        chdir: /home/ubuntu/gc
        executable: /bin/bash
